---
title: "coffee_roasting"
output: html_document
---
```{r Setup, include = FALSE}
# Set working directory to where this notebook is saved
knitr::opts_chunk$set(echo = FALSE, comment = NA, warning = FALSE, error = FALSE, message = FALSE, tidy = TRUE, global.par = TRUE, knitr.table.format = "html")
knitr::opts_knit$set(root.dir = '/...')
```

```{r Load Libraries}
# setwd("W:/HSSA/Keep/Jaclyn Ziebert/R/CSV") # if you want to change wd, put this in the code block
# install.packages("tidyverse", repo = 'https://cran.R-project.org')  try this to install packages in base R, not RStudio

library(tidyverse)    # includes tidyr, tibble, and more
library(lubridate)    # for working with dates, need this for data import
library(readxl)
library(ggtext)       # HTML for charts
library(ggrepel)
library(plotly)
library(crosstalk)
# library(data.table)   # db files are loaded as a data table, need this package
# library(janitor)      # make tabyl, adorn_totals
# library(rlang)        # {{variable}} to make ggplot2 functions
# library(kableExtra)   # styling for HTML

```

```{r}

open_profile_as_json <-
  function(alog_input = input$roast_curves_upload$datapath, country = input$country, region = input$region) {
    
    # Reads and puts it in a long string
    sub <- readLines(alog_input)

    # Must replace ' and change True/False so it has quotes in order to read as a JSON
    sub <- gsub("\\'", '"', sub)
    sub <- gsub("True", '\"True\"', sub)
    sub <- gsub("False", '\"False\"', sub)
    
    # Convert file from JSON in R format
    profile <- jsonlite::fromJSON(sub)

    # Create filename based on roast date, country and region
    filename <- sprintf(
      "%s%s-%s-%s-%s.json",
      "/roast_profiles_json/",
      # location to save
      country,
      region,
      profile$roastisodate,
      gsub(":", "-", profile$roasttime))
    
    # Also save to /data
    write(sub, paste0("C:/W_shortcut/coffee_roasting/",filename))

    # Need to get the entire filename and make a list so we can append to all_inputs_to_save
    save_filename <- c("filename" = filename) %>% as.list()
    return(save_filename)
  }

# json      <- lapply(sub,fromJSON)

# read.csv("C:/W_shortcut/coffee_roasting/data/21-02-17_1840_ZambiaKasama_1stcrack.alog", header = FALSE, quote = "[", sep = ",")
# jsonlite::read_json("C:/W_shortcut/coffee_roasting/data/21-02-17_1840_ZambiaKasama_1stcrack.alog")
# fread("C:/W_shortcut/coffee_roasting/data/21-02-17_1840_ZambiaKasama_1stcrack.alog")
# read.table("C:/W_shortcut/coffee_roasting/data/21-02-17_1840_ZambiaKasama_1stcrack.alog", sep =":")

# True with \"True\"
library(rjson)
# json.text <- readLines("C:/W_shortcut/coffee_roasting/data/21-02-17_1840_ZambiaKasama_1stcrack.alog")
# parse JSON into named list
sub <- readLines("C:/W_shortcut/coffee_roasting/data/21-02-17_1840_ZambiaKasama_1stcrack.alog")
sub <- gsub("\\'",'"',sub)
sub <- gsub("True",'\"True\"',sub)
sub <- gsub("False",'\"False\"',sub)
# json      <- lapply(sub,fromJSON)
json <- fromJSON(sub)
ms(json$timex)
mdy(json$roastdate)
sf <- data.frame(Time1 = json$timex, BT=json$temp1)
events <- data.frame(eventtime = json$specialevents, event = json$specialeventsStrings)
 plot_ly(
            # BT Line
            sf,
            type = 'scatter',
            mode = 'lines',
            x = ~as_datetime(Time1),
            line = list(color = "#4DB848"),
            # x = ~seq(ms("00:00"), ms("10:10")),
            # x = ~ lubridate::ms(Time2),
            # x = ~ lubridate::as_datetime(Time1),
            y = ~ BT,
            # hovertemplate = paste('%{y: .1f}\u00b0F', '<br>%{x}<br>'),
            hovertemplate = '%{y: .1f}\u00b0F',
            showlegend = FALSE,
            name = "BT"
        ) %>% 
    add_annotations(
      # events,
                x =  ~as_datetime(events$eventtime),
                y = ~ 300,
                text = ~ events$event,
                # yaxis = "y2",
                textposition = "top center",
                arrowhead = .5,
                arrowwidth = 1,
                font = list(size = 12)
                # bgcolor = ~ event_color
            ) %>% 
   add_segments( x = ~as_datetime(events$eventtime), xend = ~as_datetime(events$eventtime), y =~ 0, yend=~500,
                          # opacity = 1,
                          line = list(dash="dash",
                                      color = '#AAAAAA',
                                      width = 2), text = ~as_datetime(events$event))
# haiti <- readxl::read_xlsx("C:/W_shortcut/coffee_roasting/21-02-09_2015_Haiti_Baptiste.xlsx", skip = 3) %>% select(1:6) %>% rename(change_BT = "Δ BT")
# haiti$Time2 %>% typeof()
haiti <- haiti %>% mutate(Time2 = lubridate::ms(Time2), Time1 = lubridate::ms(Time1))
# haiti$Time2 <- as.POSIXct(haiti$Time2, format="%M:%S")
```
```{r}
# could also change height of fan
# maillard rgb(247,198,111)
haiti[grepl("Heat", haiti$Event), "event_color" ] <- "#f71212"
haiti[grepl("Fan", haiti$Event), "event_color" ] <- "#0d0dff"
haiti[grepl("FC", haiti$Event), "event_color" ] <- "#c5a872"
haiti[grepl("Dry End", haiti$Event), "event_color" ] <- "#77b36f"
haiti[grepl("Charge", haiti$Event), "event_color" ] <- "#222921"

# haiti$event_color %>% typeof()

# haiti <- haiti %>% mutate(anno_loc = ifelse(grepl("Heat", haiti$Event), BT + 30, BT))
```



```{r setup, include=FALSE}
# haiti <- read.csv("C:/coffee_roasting/21-02-09_2015_Haiti_Baptiste.csv", sep = "\t") %>% select(1:5) %>% janitor::row_to_names(row_number = 1) #%>% na.omit()
# haiti$Time2 <- as.POSIXct(haiti$Time2, format="%M:%S")
# haiti <- haiti %>% mutate(ET = as.numeric(ET), BT = as.numeric(BT))
# haiti %>% mutate(Time2 = as.POSIXct(Time2, format = "%M:%S")) , Time2 = lubridate::ms(Time2)
# lubridate::ms("00:09")
```



```{r  theme_ggplot2, echo = FALSE}
theme_coffee_charts <- function(base_size = 12) {
  theme_classic(base_size = base_size) %+replace%
    theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_text(size = base_size),
    panel.grid.major.x = element_line(color = "black"),
    legend.position = "none",
    strip.background=element_rect(fill="#CCD2D4", colour="transparent"),
    strip.text  =element_markdown(size = base_size, hjust = 0, margin=margin(0,0,2,2)),
    plot.title.position = "plot",
    plot.caption.position =  "plot",
    plot.title = element_markdown(lineheight = 1.1, size = base_size + 2, hjust = 0, margin=margin(0,0,5,0)), # for title colors
    plot.caption = element_text(hjust = 0, face= "italic")
    # legend.text = element_markdown(size = 11)
    )
}

# Changing the default theme
theme_set(theme_coffee_charts())
```

```{r,  fig.width=12,fig.height=6}

haiti %>% filter(!is.na(Time2)) %>% ggplot() + geom_rect(aes(
  xmin = lubridate::ms("00:00"),
  xmax = lubridate::ms("08:00"),
  ymin = 0,
  ymax = 100
),
fill = "#d9ecd9") + geom_rect(aes(
  xmin = lubridate::ms("00:00"),
  xmax = lubridate::ms("08:00"),
  ymin = 100,
  ymax = 300
),
fill = "#fff1d9") + geom_rect(aes(
  xmin = lubridate::ms("00:00"),
  xmax = lubridate::ms("08:00"),
  ymin = 300,
  ymax = 500
),
fill = "#efe8e0") + # FC area
  geom_rect(aes(
  xmin = haiti$Time2[grepl("FCs", haiti$Event), "Time2"],
  xmax = haiti$Time2[grepl("FCe", haiti$Event), "Time2"],
  ymin = 0,
  ymax = 500
),
fill = "#efe8e0") +
  scale_y_continuous(expand = expansion(mult = c(0, .05)),
                     name = "") +
  theme_coffee_charts() +
  geom_line(aes(x = Time2, y = ET), color = "#ff0000", size = 2) + # ET
  scale_x_time(expand = expansion(mult = c(0, .05)), name = "") +
  geom_line(aes(x = Time2, y = BT), color = "#00007f", size = 2) +
  geom_line(aes(x = Time2, y = change_BT *6.25),
            color = "#0000ff",
            size = 2) +
  geom_label_repel(
    aes(x = Time2, y = BT,
      label = Event),
      # fill = as.character(event_color),
      # color = "#ffffff",
      segment.colour = "black"
      # fontface = 'bold',
      # box.padding = unit(0.35, "lines"),
      # point.padding = unit(0.5, "lines")
    
  ) +
  labs(
    title = "<span style='font-size:16pt'>
    <span style='color:#00007f;'>**BT**</span>,
    <span style='color:#ff0000;'>**ET**</span>,
    <span style='color:#0000ff;'>**Change BT**</span> F
    </span>"
  )

plotly::ggplotly(gg) %>% add_annotations(x = ~ Time2,  y = ~ BT, text= ~Event, textposition = "top right", font = list(color = "#ffffff"), bgcolor= ~event_color) 
```
```{r plotly, fig.width=12,fig.height=6}

time_zero = as_datetime("1970-01-01 00:00:00 UTC")
time_max = max(as_datetime(haiti$Time2), na.rm = TRUE)
dry_end = as_datetime(haiti$Time2[grepl("Dry End", haiti$Event), "Time2"])
first_crack_start = as_datetime(haiti$Time2[grepl("FCs", haiti$Event), "Time2"])
first_crack_end = as_datetime(haiti$Time2[grepl("FCe", haiti$Event), "Time2"])
drop_start = as_datetime(haiti$Time2[grepl("Drop", haiti$Event), "Time2"])
max_temp = 500 # Highest temp in chart

plot_ly( # BT Line
  haiti,
  type = 'scatter',
  mode = 'lines',
  x = ~ lubridate::as_datetime(Time2),
  line = list(color = "#4DB848"),
  # x = ~seq(ms("00:00"), ms("10:10")),
  # x = ~ lubridate::ms(Time2),
  # x = ~ lubridate::as_datetime(Time1),
  y = ~ BT,
  # hovertemplate = paste('%{y: .1f}\u00b0F', '<br>%{x}<br>'),
  hovertemplate = '%{y: .1f}\u00b0F',
  showlegend = FALSE,
  name = "BT"
) %>%
  add_trace( # ET Line
    mode = 'lines',
    x = ~ lubridate::as_datetime(Time2),
    y = ~ ET,
    line = list(color = "#D50032"),
    name = "ET"
  ) %>%
  add_trace( # Change BT Line
    mode = 'lines',
    x = ~ lubridate::as_datetime(Time2),
    y = ~ change_BT,
    line = list(color = "#428BCA"),
    name = "\u0394BT",
    yaxis = "y2"
  ) %>% layout(hovermode = "x unified") %>% 
  filter(!is.na(Event),
         !is.na(Time2),
         Event != "Drop",
         !grepl("^Charge", Event)) %>%
  add_annotations(
    # x =  ~jitter(Time2), 
    # y = ~jitter(BT, 30),
    text = ~ Event,
    textposition = "top center",
    arrowhead = .5,
    arrowwidth = 1,
    font = list(size = 12, color = "#ffffff"),
    bgcolor = ~ event_color
  ) %>%
  layout( # The right side y-axis
    yaxis2 = list(
    zeroline = F,
    showline = F,
    showgrid = F,
    tickfont = list(color = "#428BCA"),
    ticksuffix = "\u00b0F",
    overlaying = "y",
    side = "right",
    title = ""
),
    shapes = list(
      list(
        type = rect,
        x0 = time_zero,
        x1 = dry_end,
        y0 = 0,
        y1 = max_temp,
        line = list(color = '#d9ecd9'),
        fillcolor = '#d9ecd9',
        opacity = 0.2,
        layer = 'below'
      ),
      list(
        type = rect,
        x0 = dry_end,
        x1 = first_crack_start,
        y0 = 0,
        y1 = max_temp,
        line = list(color = '#fff1d9'),
        fillcolor = '#fff1d9',
        opacity = 0.2,
        layer = 'below'
      ),
      list(
        type = rect,
        x0 = first_crack_start,
        x1 = drop_start,
        y0 = 0,
        y1 = 500,
        line = list(color = '#efe8e0'),
        fillcolor = '#efe8e0',
        opacity = 0.2,
        layer = 'below'
      )
    ),
    xaxis = list(
      # gridcolor = toRGB("gray85"),
      title = "",
      zeroline = F,
      showline = F,
      showgrid = F,
      tick0 = time_zero,
      ticks = "inside",
      tickcolor = "grey80",
      tickformat = "%M:%S",
      dtick = 30000 # Tick every 30 seconds
    ),
    yaxis = list(
      title = "",
      ticksuffix = "\u00b0F",
      zeroline = F,
      showline = F,
      showgrid = F
    ),
    margin = list(
      r = 30,
      l = 0,
      b = 0,
      t = 0
    )
  )

haiti %>% filter(!is.na(Event)) %>% DT::datatable()
```

```{r}

        time_zero = as_datetime("1970-01-01 00:00:00 UTC")
        time_max = max(as_datetime(haiti$Time2), na.rm = TRUE)
        dry_end = as_datetime(haiti$Time2[grepl("Dry End", haiti$Event), "Time2"])
        first_crack_start = as_datetime(haiti$Time2[grepl("FCs", haiti$Event), "Time2"]) 
        first_crack_end = as_datetime(haiti$Time2[grepl("FCe", haiti$Event), "Time2"])
        drop_start = as_datetime(haiti$Time2[grepl("Drop", haiti$Event), "Time2"])
        max_temp = 500 # Highest temp in chart

        # Get temps are event times, returns a list
get_roasting_profile_data <- function(df) {
  chart_analysis <- c(
    time_zero = "1970-01-01 00:00:00 UTC",
    charge_start = format(as_datetime(df$Time2[grepl("Charge", df$Event), "Time2"]), format = "%M:%S"),
    time_max = format(max(as_datetime(df$Time2), na.rm = TRUE), format = "%M:%S"),
    dry_end = format(as_datetime(df$Time2[grepl("Dry End", df$Event), "Time2"]), format = "%M:%S"),
    first_crack_start = format(as_datetime(df$Time2[grepl("FCs", df$Event), "Time2"]), format =  "%M:%S"),
    first_crack_end = format(as_datetime(df$Time2[grepl("FCe", df$Event), "Time2"]), format = "%M:%S"),
    drop_start = format(as_datetime(df$Time2[grepl("Drop", df$Event), "Time2"]), format = "%M:%S"),
    # max_temp = 500,
    # Highest temp in chart
    end_temp = as.numeric(df[grepl("Drop", df$Event), "BT"])
  ) %>% as.list()
  
  chart_analysis
}
chart_analysis <- get_roasting_profile_data(haiti)


# Do calculations, finalize numbers and time to make into a table
chart_analysis <-
chart_analysis %>% as.data.frame() %>% mutate(duration = ms(drop_start)-ms(charge_start), dev_time = ms(drop_start) - ms(first_crack_start), duration = format(as_datetime(duration), format="%M:%S"),dev_ratio = paste0(round(ms(dev_time) *100 / ms(duration),1),"%"), dev_time = format(as_datetime(dev_time), format="%M:%S"), end_temp = round(as.numeric(end_temp), 1)) %>% mutate_all(as.character) %>% select("First crack" = first_crack_start, "Roast duration" = duration, "Development time" = dev_time, "Dev. time ratio" = dev_ratio, "End temp." = paste0(end_temp,"\u00b0F"))

library(formattable)
# make a datatable for output
chart_analysis %>% pivot_longer(cols = 1:5, values_to = "data") %>% formattable(., list(
  name = formatter("span", style = "color:#AAAAAA; font-size:14px; font-weight:bold;"),
  data = formatter("span", style = "color:grey;")
))
# area()~formatter("span", style = " border:0;")
heae(chart_analysis)
cat("<style>th {border: none;
 display: none;
}</style>
")
# R <- strptime(R, format="%M:%S") Converts to POSIXt, or use format(R, format="%M:%S")
```


```{r tasting, fig.height= 10, fig.width=10}
# coffee = read.csv('C:/W_shortcut/coffee_roasting/data/coffee-flavors_counterculture.csv')
# coffee = readxl::read_xlsx('C:/W_shortcut/coffee_roasting/data/coffee-flavors_lexicon.xlsx')
        plot_ly() %>% add_trace(
            type='sunburst',
            ids=coffee$ids,
            labels=coffee$end_name,
            parents=coffee$parents,
            domain=list(column=1),
            maxdepth=3,
            insidetextorientation='radial'
            # markers = list(colors = ("red"))
        ) #%>% layout(sunburstcolorway = ~coffee$colors)
```
```{r}
library(leaflet)

qquery <- highlight_key(haiti)

p <- plot_ly(
  qquery,
  type = 'scatter',
  mode = 'markers',
  x = ~ lubridate::as_datetime(Time2),
  line = list(color = "#00007f"),
  # x = ~seq(ms("00:00"), ms("10:10")),
  # x = ~ lubridate::ms(Time2),
  # x = ~ lubridate::as_datetime(Time1),
  y = ~ BT,
  # hovertemplate = paste('%{y: .1f}\u00b0F', '<br>%{x}<br>'),
  hovertemplate = '%{y: .1f}\u00b0F',
  showlegend = FALSE,
  name = "BT"
) %>%
  highlight("plotly_selected", dynamic = TRUE)

map <- DT::datatable(qquery)

# persistent selection can be specified via options()
withr::with_options(
  list(persistent = TRUE), 
  crosstalk::bscols(widths = c(6, 6), p, map)
)
```
```{r json flatten}
js %>% as.data.frame()
jsonlite::flatten(js)
```

